// Code generated by sqlc. DO NOT EDIT.
// source: cart_item.sql

package db

import (
	"context"
)

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_item (quantity,
                       cart_id,
                       product_id)
VALUES ($1, $2, $3)
RETURNING id, quantity, cart_id, product_id
`

type CreateCartItemParams struct {
	Quantity  int64 `json:"quantity"`
	CartID    int64 `json:"cart_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, createCartItem, arg.Quantity, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.Quantity,
		&i.CartID,
		&i.ProductID,
	)
	return i, err
}
