// Code generated by sqlc. DO NOT EDIT.
// source: cart.sql

package db

import (
	"context"
)

const createCart = `-- name: CreateCart :one
INSERT INTO cart (total_price, vat, discount, status)
VALUES ($1, $2, $3, $4)
RETURNING id, total_price, vat, discount, customer_id, status, created_at, updated_at
`

type CreateCartParams struct {
	TotalPrice int64      `json:"total_price"`
	Vat        int64      `json:"vat"`
	Discount   int64      `json:"discount"`
	Status     CartStatus `json:"status"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart,
		arg.TotalPrice,
		arg.Vat,
		arg.Discount,
		arg.Status,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.TotalPrice,
		&i.Vat,
		&i.Discount,
		&i.CustomerID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
