// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: order.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO "order" (total_price, customer_id)
VALUES ($1, $2)
`

type CreateOrderParams struct {
	TotalPrice int64 `json:"total_price"`
	CustomerID int64 `json:"customer_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder, arg.TotalPrice, arg.CustomerID)
	return err
}
